[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "func_adl/_version.py"

[tool.isort]
profile = "black"

[tool.black]
line-length = 99
